# Generated by Django 5.2.3 on 2025-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l'utilisateur est un administrateur",
            ),
        ),
    ]
