# Generated by Django 5.2.3 on 2025-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectiveMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "larval_stage",
                    models.CharField(
                        help_text="Stade larvaire (ex: L1, L2, ...)", max_length=50
                    ),
                ),
                (
                    "measure",
                    models.TextField(help_text="Mesure corrective ou conseil à suivre"),
                ),
            ],
        ),
    ]
