# Generated by Django 5.2.3 on 2025-08-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_userprofile_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
