# Generated by Django 5.2.3 on 2025-08-08 14:21

import recognition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="image",
            field=models.ImageField(upload_to=recognition.models.user_directory_path),
        ),
    ]
