# Generated by Django 5.2.3 on 2025-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_alter_observation_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correctivemeasure",
            name="larval_stage",
        ),
        migrations.AddField(
            model_name="correctivemeasure",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, help_text="Ordre d'affichage des mesures", null=True
            ),
        ),
    ]
