# Generated by Django 5.2.3 on 2025-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0005_remove_correctivemeasure_larval_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
